### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by roi35** [johncantrell97/bip39-solver-gpu#3]
Hello, can u add target list address (.txt) file?   1 address per line. And use random mode generation seed (mnemonic) thanks. Very need

**Comment by roi35** [comment]
please please do it. so that you can add all addresses with balances, and randomly generate  seeds to them...

**Comment by roi35** [comment]
Please very need this option (mode)

**Comment by roi35** [comment]
please answer me is this possible?

**Comment by johncantrell97** [comment]
this is possible but I'm not actively working on this project.  this was developed as part of the giveaway I was trying to win and I decided to open source it in case anyone was interested in seeing what I did.

**Comment by roi35** [comment]
it would be good if you did it, I would pay you for it
